#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDwVO+a3o7oNp99Bnyolp6Q9T0CfIokWeANz9t6mQtcYKKqUxJ3fyU00yOPaj2XLoOwPF0Tp5/rMU5DLzu6nrY2ymQGMWb5dFN4J3YmOaXI9T/iCgNafeVvW1LxCtxT+tqN5LzMXiykpCrh58NhBnshrGFycjml3vva56Vi4ZQS3MQp8JRrnL3XWZiAKyzkJRvSgc81G0ox9JL5Uq5FF1cuOwGr90gJ70/0f5TfAdn5UDsPDdHK9ZZfziqj1DvnWTLtPdFrDmjDAH/7wJUc5/Qv1gTiZkHxXkJmNWMrHjNuur/Qtn3kARXYNgeP2KuqWsuxPvbOsc6Xm/YrCDVeS/7gah4NKZAprlEqA42yJB1j9Zx8uu+C3sTP8CdZHg0JdiV7O4nNe0MI4sVYrFjJQ8jZtYD7E2XgeJxxE1dEyTe+UvRQycY/dv83QSNiLFWR7Wh0dKVROD8NS8932v/ggWfuJpMy9q8QtWaU3+rKGCAcNODv0N4qubnyZvSgmwDb3VE= priotto@priotto-pc
resize_rootfs: true
package_update: true
package_upgrade: true
packages:
  - htop
users:
  - default
  - name: ubuntu
    gecos: Ubuntu
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
system_info:
  default_user:
    name: ubuntu
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]


